version: '3'
services: 
  mongo:
    container_name: mongodb
    image: 'mongo:latest'
    volumes:
      - data:/data/db
    ports: 
      - '27017:27017'
    command: mongod
  wi-uservice:
    build: .
    depends_on:  
      - mongo
    ports:
      - '5002:5001'
volumes: 
  data:
    