swagger: "2.0"

info:
  title: "WIPM"
  version: "1.0"
  description: "WI machine learning service"

schemes:
- http
- https

basePath: "/api"

paths:
  /data:
    post:
      operationId: src.controllers.data.create
      description: "Create bucket data"
      parameters:
      - in: "body"
        name: "body"
        schema:
          type: "object"
          required:
          - bucket_id
          - dims
          properties:
            bucket_id:
              type: "string"
            dims:
              type: "integer"
      responses:
        201:
          description: "Create bucket success"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
              bucket_id:
                type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    put:
      operationId: src.controllers.data.push
      description: "Push data into bucket"
      parameters:
      - in: "body"
        name: "body"
        schema:
          type: "object"
          required:
          - bucket_id
          - data
          properties:
            bucket_id:
              type: "string"
            data:
              $ref: "#/definitions/Features"
      responses:
        201:
          description: "Push data success"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    delete:
      operationId: src.controllers.data.delete
      description: "Delete bucket data"
      parameters:
      - in: "body"
        name: "body"
        schema:
          type: "object"
          required:
          - bucket_id
          properties:
            bucket_id:
              type: "string"
      responses:
        201:
          description: "Delete bucket success"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"

  /model/train:
    post:
      operationId: src.controllers.train
      description: "Training model"
      parameters:
      - in: "body"
        name: "body"
        schema:
          type: "object"
          required:
          - model_id
          - features
          - target
          properties:
            model_id:
              type: "string"
            features:
              $ref: "#/definitions/Features"
            target:
              $ref: "#/definitions/Curve"
      responses:
        201:
          description: "Training success"
          schema:
            type: "object"
            required:
            - message
            properties:
              status:
                type: string
                enum: 
                - started
                - pending
                - success
                - error
              message:
                type: "string"
              mean_squared_error:
                type: "number"
              mean_absolute_error:
                type: "number"
              train_loss:
                $ref: "#/definitions/Curve"
              val_loss:
                $ref: "#/definitions/Curve"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"

  /model/predict:
    post:
      operationId: src.controllers.predict
      description: "Predict model"
      parameters:
        - in: "body"
          name: "body"
          schema:
            type: "object"
            required:
            - model_id
            - features
            properties:
              model_id:
                type: "string"
              features:
                $ref: "#/definitions/Features"
      responses:
        201:
          description: "Predict success"
          schema:
            type: "object"
            required:
            - message
            - target
            properties:
              message:
                type: "string"
              target:
                $ref: "#/definitions/Curve"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"

  /model/train_by_bucket_data:
    post:
      operationId: src.controllers.train_by_bucket_data
      description: "Training model"
      parameters:
      - in: "body"
        name: "body"
        schema:
          type: "object"
          required:
          - model_id
          - bucket_id
          properties:
            model_id:
              type: "string"
            bucket_id:
              type: "string"
      responses:
        201:
          description: "Training success"
          schema:
            type: "object"
            required:
            - message
            properties:
              status:
                type: string
                enum: 
                - started
                - pending
                - success
                - error
              message:
                type: "string"
              mean_squared_error:
                type: "number"
              mean_absolute_error:
                type: "number"
              train_loss:
                $ref: "#/definitions/Curve"
              val_loss:
                $ref: "#/definitions/Curve"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  
  /model/create/huber:
    post:
      operationId: src.controllers.create.huber
      tags:
      - create
      description: "Create Huber model"
      parameters:
        - in: "body"
          name: "body"
          schema:
            $ref: "#/definitions/Huber"
      responses:
        201:
          description: "Create Huber model success"
          schema:
              $ref: "#/definitions/CreateSuccess"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"


  /bucket/list:
    get:
      operationId: src.controllers.get_list_buckets
      description: Returns all buckets in database 
      responses:
        200:
          description: Get list bucket in database
          schema:
            $ref: '#/definitions/Error'
        
          
definitions:
  Error:
    type: "object"
    required:
    - message
    properties:
      message:
        type: "string"

  CreateSuccess:
    type: "object"
    properties:
      message:
        type: "string"
      model_id:
        type: "string"

  Curve:
    type: "array"
    items:
      type: "number"

  Features:
    type: "array"
    items:
      $ref: "#/definitions/Curve"
  KNearestNeighborsClassifier:
    type: "object"
    properties:
      model_id:
        type: "string"
        example: "test_k_nearest_neighbors_classifier_01"
      num_neighbors:
        type: "integer"
        example: 100
      p:
        type: "integer"
        example: 1
      metric:
        type: "string"
        example: minkowski