swagger: "2.0"

info:
  title: "WIPM"
  version: "1.0"
  description: "WI machine learning service"

schemes:
- http
- https

basePath: "/"

paths:
  /:
    get:
      operationId: src.controllers.dummy
      summary: "Test"
      description: "Làm ơn đi mà"
      responses:
        200:
          description: Combination Ensemble SOM