swagger: "2.0"

info:
  title: "WIPM"
  version: "1.0"
  description: "WI machine learning service"

schemes:
- http
- https

basePath: "/api"

paths:
  /data:
    post:
      operationId: src.controllers.data.create
      description: "Create bucket data"
      parameters:
      - in: "body"
        name: "body"
        schema:
          type: "object"
          required:
          - bucket_id
          - dims
          properties:
            bucket_id:
              type: "string"
            dims:
              type: "integer"
      responses:
        201:
          description: "Create bucket success"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
              bucket_id:
                type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    put:
      operationId: src.controllers.data.push
      description: "Push data into bucket"
      parameters:
      - in: "body"
        name: "body"
        schema:
          type: "object"
          required:
          - bucket_id
          - data
          properties:
            bucket_id:
              type: "string"
            data:
              $ref: "#/definitions/Features"
      responses:
        201:
          description: "Push data success"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    delete:
      operationId: src.controllers.data.delete
      description: "Delete bucket data"
      parameters:
      - in: "body"
        name: "body"
        schema:
          type: "object"
          required:
          - bucket_id
          properties:
            bucket_id:
              type: "string"
      responses:
        201:
          description: "Delete bucket success"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"

  /model/train:
    post:
      operationId: src.controllers.train
      description: "Training model"
      parameters:
      - in: "body"
        name: "body"
        schema:
          type: "object"
          required:
          - model_id
          - features
          - target
          properties:
            model_id:
              type: "string"
            features:
              $ref: "#/definitions/Features"
            target:
              $ref: "#/definitions/Curve"
      responses:
        201:
          description: "Training success"
          schema:
            type: "object"
            required:
            - message
            properties:
              status:
                type: string
                enum: 
                - started
                - pending
                - success
                - error
              message:
                type: "string"
              mean_squared_error:
                type: "number"
              mean_absolute_error:
                type: "number"
              train_loss:
                $ref: "#/definitions/Curve"
              val_loss:
                $ref: "#/definitions/Curve"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"

  /model/predict:
    post:
      operationId: src.controllers.predict
      description: "Predict model"
      parameters:
        - in: "body"
          name: "body"
          schema:
            type: "object"
            required:
            - model_id
            - features
            properties:
              model_id:
                type: "string"
              features:
                $ref: "#/definitions/Features"
      responses:
        201:
          description: "Predict success"
          schema:
            type: "object"
            required:
            - message
            - target
            properties:
              message:
                type: "string"
              target:
                $ref: "#/definitions/Curve"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"

  /model/train_by_bucket_data:
    post:
      operationId: src.controllers.train_by_bucket_data
      description: "Training model"
      parameters:
      - in: "body"
        name: "body"
        schema:
          type: "object"
          required:
          - model_id
          - bucket_id
          properties:
            model_id:
              type: "string"
            bucket_id:
              type: "string"
      responses:
        201:
          description: "Training success"
          schema:
            type: "object"
            required:
            - message
            properties:
              status:
                type: string
                enum: 
                - started
                - pending
                - success
                - error
              message:
                type: "string"
              mean_squared_error:
                type: "number"
              mean_absolute_error:
                type: "number"
              train_loss:
                $ref: "#/definitions/Curve"
              val_loss:
                $ref: "#/definitions/Curve"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  
  /model/create/neural_network:
    post:
      operationId: src.controllers.create.neural_network_classifier
      tags:
      - create
      description: "Create Neural Network Classification model"
      parameters:
        - in: "body"
          name: "body"
          schema:
            $ref: "#/definitions/NeuralNetworkClassifier"
      responses:
        201:
          description: "Create NeuralNetworkClassifier model success"
          schema:
              $ref: "#/definitions/CreateSuccess"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"

  
  /bucket/list:
    get:
      operationId: src.controllers.get_list_buckets
      description: Return all buckets in database
      responses:
        200:
          description: Get list bucket successfully
          schema:
            $ref: '#/definitions/Error'
          
definitions:
  Error:
    type: "object"
    required:
    - message
    properties:
      message:
        type: "string"

  CreateSuccess:
    type: "object"
    properties:
      message:
        type: "string"
      model_id:
        type: "string"

  Curve:
    type: "array"
    items:
      type: "number"

  Features:
    type: "array"
    items:
      $ref: "#/definitions/Curve"

  NeuralNetworkClassifier:
    type: "object"
    properties:
      model_id:
        type: "string"
        example: "test_neural_network_classifier_01"
      hidden_layer_sizes:
        type: "array"
        items:
          type: integer
        example: [10, 20, 10]
      activation:
        type: "string"
        example: elu
      algorithm:
        type: "string"
        example: backprop
      num_epochs:
        type: "integer"
        example: 1000
      optimizer:
        type: "string"
        example: nadam
      learning_rate:
        type: "number"
        example: 0.001
      warm_up:
        type: "boolean"
      decay:
        type: "number"
        example: 0.0000010
      population:
        type: "integer"
        example: 50
      sigma:
        type: "number"
        example: 0.01
      boosting_ops:
        type: "integer"
        example: 0
