swagger: "2.0"

paths:
  random_forest:
    post:
      operationId: random_forest
      description: "Create Random Forest Regression model"
      parameters:
        - in: "body"
          name: "body"
          schema:
            $ref: "#/definitions/RandomForest"
      responses:
        201:
          description: "Create Random Forest model success"
          schema:
              $ref: "#definitions/CreateSuccess"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"

definitions:
  RandomForest:
    type: "object"
    properties:
      n_estimators:
        type: "integer"
        example: 20
      criterion:
        type: "string"
        example: "mse"
      max_depth:
        type: "integer"
        example: 3
      max_features:
        type: "integer"
        example: 2
      bootstrap:
        type: "boolean"
        example: True
      random_state:
        type: "integer"
        example: 0
