swagger: "2.0"

paths:
  neural_network:
    post:
      operationId: neural_network
      description: "Create Neural Network model"
      parameters:
        - in: "body"
          name: "body"
          schema:
            $ref: "#/definitions/NeuralNetwork"
      responses:
        201:
          description: "Create Neuarl Network model success"
          schema:
              $ref: "#definitions/CreateSuccess"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"

definitions:
  NeuralNetwork:
    type: "object"
    properties:
      solver:
        type: "string"
        example: "lbfgs"
      activation:
        type: "string"
        example: "relu"
      max_iter:
        type: "integer"
        example: 100
      learning_rate_init:
        type: "number"
        example: 0.005
      tol: 
        type: "number"
        example: 0.0003
      hidden_layer_sizes:
        type: "array"
        items:
          type: "integer"
        example: [10, 10]

