swagger: "2.0"

paths:
  linear_regression:
    post:
      operationId: linear_regression
      description: "Create Linear Regression  model"
      parameters:
        - in: "body"
          name: "body"
          schema:
            $ref: "#/definitions/LinearRegression"
      responses:
        201:
          description: "Create Linear Regression  model success"
          schema:
              $ref: "#definitions/CreateSuccess"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"

definitions:
  LinearRegression:
    type: "object"
    properties:
      degree:
        type: "integer"
