swagger: "2.0"

paths:
  xgboost:
    post:
      operationId: xgboost
      description: "Create XGBoost model"
      parameters:
        - in: "body"
          name: "body"
          schema:
            $ref: "#/definitions/XGBoost"
      responses:
        201:
          description: "Create XGBoost model success"
          schema:
              $ref: "#definitions/CreateSuccess"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"

definitions:
  Xgboost:
    type: "object"
    properties:
      n_estiamtors:
        type: "integer"
        example: 100
      max_depth:
        type: "integer"
        example: 3
      gamma:
        type: "number"
        example: 0.01
      booster:
        type: "string"
        example: "gbtree"
      reg_alpha:
        type: "number"
        example: 0.0
      reg_lamda:
        type: "number"
        example: 1.0
      random_state:
        type: "integer"
        example: 1
