swagger: "2.0"

paths:
  lasso:
    post:
      operationId: lasso
      description: "Create Lasso model"
      parameters:
        - in: "body"
          name: "body"
          schema:
            $ref: "#/definitions/Lasso"
      responses:
        201:
          description: "Create lasso model success"
          schema:
              $ref: "#definitions/CreateSuccess"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"

definitions:
  Lasso:
    type: "object"
    properties:
      max_iter:
        type: "integer"
        default: 10
      alpha:
        type: "number"
        default: 1.0
      tol:
        type: "number"
        default: 0.0001
