swagger: "2.0"

paths:
  svm:
    post:
      operationId: svm
      description: "Create Support Vector Machine model"
      parameters:
        - in: "body"
          name: "body"
          schema:
            $ref: "#/definitions/SVM"
      responses:
        201:
          description: "Create Support Vector Machine model success"
          schema:
              $ref: "#definitions/CreateSuccess"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
            
definitions:
  SVM:
    type: "object"
    properties:
      kernel:
        type: "string"
      C:
        type: "number"
      gamma:
        type: "number"
      degree:
        type: "integer"
      tol:
        type: "number"
      max_iter:
        type: "integer"
