swagger: "2.0"

paths:
  xgboost:
    post:
      operationId: xgboost
      description: "Create XGBoost model"
      parameters:
        - in: "body"
          name: "body"
          schema:
            $ref: "#/definitions/XGBoost"
      responses:
        201:
          description: "Create XGBoost model success"
          schema:
              $ref: "#definitions/CreateSuccess"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"

definitions:
  XGBoost:
    type: "object"
    properties:
      n_estiamtors:
        type: "integer"
      max_depth:
        type: "integer"
      gamma:
        type: "number"
      booster:
        type: "string"
      reg_alpha:
        type: "number"
      reg_lamda:
        type: "number"
